# Generated by Django 4.1.7 on 2023-03-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0007_alter_note_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="note", to="notes.tag"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
