# Generated by Django 4.1.7 on 2023-03-20 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0009_alter_tag_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="tags",
        ),
        migrations.AddField(
            model_name="tag",
            name="note",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="notes.note",
            ),
            preserve_default=False,
        ),
    ]
