# Generated by Django 4.1.7 on 2023-05-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0011_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
