# Generated by Django 4.1.7 on 2023-05-18 05:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0012_alter_post_body"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
    ]
