# Generated by Django 4.1.7 on 2023-05-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0014_safedeletemodel_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="safedeletemodel",
            name="deleted_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="safedeletemodel",
            name="deleted_by",
            field=models.CharField(default="", max_length=255, null=True),
        ),
    ]
